/**
 * Mã lỗi nghiệp vụ toàn hệ thống — được Exception Filter đọc và trả về field `errorCode`.
 * Quy tắc đặt tên: PREFIX_NOUN_ACTION (UPPER_SNAKE_CASE)
 * Prefix theo module: AUTH_*, RBAC_*, USER_*, BOOKING_*, ORDER_*, PAYMENT_*, CINEMA_*, MEDIA_*
 */
export enum ErrorCode {
  // ─── GENERIC ───────────────────────────────────────────────────────────────
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DATA_ALREADY_EXISTS = 'DATA_ALREADY_EXISTS',
  FOREIGN_KEY_VIOLATION = 'FOREIGN_KEY_VIOLATION',

  // ─── AUTH ──────────────────────────────────────────────────────────────────
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_PHONE_ALREADY_EXISTS = 'AUTH_PHONE_ALREADY_EXISTS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_ACCOUNT_BLOCKED = 'AUTH_ACCOUNT_BLOCKED',

  // ─── RBAC ──────────────────────────────────────────────────────────────────
  RBAC_FORBIDDEN = 'RBAC_FORBIDDEN',
  RBAC_INSUFFICIENT_PERMISSIONS = 'RBAC_INSUFFICIENT_PERMISSIONS',
  RBAC_ROLE_NOT_FOUND = 'RBAC_ROLE_NOT_FOUND',
  RBAC_PERMISSION_NOT_FOUND = 'RBAC_PERMISSION_NOT_FOUND',
  RBAC_SYSTEM_ROLE_IMMUTABLE = 'RBAC_SYSTEM_ROLE_IMMUTABLE',
  RBAC_ROLE_ALREADY_ASSIGNED = 'RBAC_ROLE_ALREADY_ASSIGNED',

  // ─── USER ──────────────────────────────────────────────────────────────────
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_BLOCKED = 'USER_ALREADY_BLOCKED',
  USER_INACTIVE = 'USER_INACTIVE',
  CANNOT_MODIFY_SUPER_ADMIN_ROLE = 'CANNOT_MODIFY_SUPER_ADMIN_ROLE',
  CANNOT_BLOCK_SELF = 'CANNOT_BLOCK_SELF',
  DEFAULT_ROLE_NOT_FOUND = 'DEFAULT_ROLE_NOT_FOUND',
  CINEPLEX_SCOPE_REQUIRED = 'CINEPLEX_SCOPE_REQUIRED',
  ACCOUNT_UNVERIFIED = 'ACCOUNT_UNVERIFIED',

  // ─── BOOKING ───────────────────────────────────────────────────────────────
  BOOKING_SEAT_ALREADY_HELD = 'BOOKING_SEAT_ALREADY_HELD',
  BOOKING_SEAT_ALREADY_SOLD = 'BOOKING_SEAT_ALREADY_SOLD',
  BOOKING_SEAT_NOT_FOUND = 'BOOKING_SEAT_NOT_FOUND',
  BOOKING_EXCEED_MAX_SEATS = 'BOOKING_EXCEED_MAX_SEATS',
  BOOKING_ISOLATED_SEAT = 'BOOKING_ISOLATED_SEAT',  // Để trống 1 ghế lẻ
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',
  BOOKING_NOT_HELD = 'BOOKING_NOT_HELD',
  BOOKING_EXPIRED = 'BOOKING_EXPIRED',
  BOOKING_ALREADY_CONFIRMED = 'BOOKING_ALREADY_CONFIRMED',
  BOOKING_SHOWTIME_NOT_BOOKABLE = 'BOOKING_SHOWTIME_NOT_BOOKABLE',

  // ─── ORDER ─────────────────────────────────────────────────────────────────
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_PAID = 'ORDER_ALREADY_PAID',
  ORDER_ALREADY_CANCELLED = 'ORDER_ALREADY_CANCELLED',
  ORDER_INVALID_STATUS = 'ORDER_INVALID_STATUS',
  ORDER_FNB_ITEM_NOT_FOUND = 'ORDER_FNB_ITEM_NOT_FOUND',
  ORDER_FNB_ITEM_UNAVAILABLE = 'ORDER_FNB_ITEM_UNAVAILABLE',

  // ─── PAYMENT ───────────────────────────────────────────────────────────────
  PAYMENT_INITIATION_FAILED = 'PAYMENT_INITIATION_FAILED',
  PAYMENT_INVALID_SIGNATURE = 'PAYMENT_INVALID_SIGNATURE',
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_REFUND_FAILED = 'PAYMENT_REFUND_FAILED',

  // ─── CINEMA ────────────────────────────────────────────────────────────────
  CINEMA_CINEPLEX_NOT_FOUND = 'CINEMA_CINEPLEX_NOT_FOUND',
  CINEMA_AUDITORIUM_NOT_FOUND = 'CINEMA_AUDITORIUM_NOT_FOUND',
  CINEMA_SEAT_NOT_FOUND = 'CINEMA_SEAT_NOT_FOUND',
  CINEMA_SHOWTIME_CONFLICT = 'CINEMA_SHOWTIME_CONFLICT',
  CINEMA_AUDITORIUM_INACTIVE = 'CINEMA_AUDITORIUM_INACTIVE',

  // ─── MEDIA / STORAGE ───────────────────────────────────────────────────────
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  MEDIA_FILE_TOO_LARGE = 'MEDIA_FILE_TOO_LARGE',
  MEDIA_INVALID_FILE_TYPE = 'MEDIA_INVALID_FILE_TYPE',
}
